name: Update Profile Trophies

on:
  schedule:
    - cron: '0 0 * * *' # Runs automatically every day at midnight
  workflow_dispatch:     # Allows you to manually trigger it anytime

jobs:
  generate-trophies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Trophies Card
        uses: soulteary/github-profile-trophy-action@v1
        with:
          options: 'username=${{ github.repository_owner }}&row=1&column=6&margin-h=8&theme=darkhub&count_private=true&margin-w=15&no-frame=true'
          path: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add trophy.svg
          git diff-index --quiet HEAD || git commit -m "chore: update profile trophies"
          git push
